# Generated by Django 4.2.11 on 2025-07-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('symptoms', models.TextField()),
                ('test_results', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('medicine_text', models.TextField(blank=True, help_text='Legacy field - comma-separated medicine names', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('healing_rate_7_days', models.FloatField(default=70, help_text='Effectiveness rating (10-100) for 7-day recovery')),
                ('typical_dosage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='symptom_checker.disease')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_symptoms', to='symptom_checker.disease')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='symptom_checker.medicine'),
        ),
    ]
