# Generated by Django 4.2.11 on 2025-07-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_is_approved_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
